name: trivia_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  html_character_entities: ^1.0.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  audioplayers: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sonne.mp3
    - assets/amerika.mp3
    - fonts/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
